### ISSUE TITLE
My style is out of order

### ISSUE THREAD

**Issue by 520131420** [christorange/VerticalFox#18]
**When I press Ctrl + H to open the history:**
![图片](https://github.com/christorange/VerticalFox/assets/89644868/b598b15e-da53-4810-92a3-303ccef0ba8a)---------![图片](https://github.com/christorange/VerticalFox/assets/89644868/cc46b849-3cba-46b0-a22f-2c8499f1e252)
**I can only restore sideberry with one click!
There are also problems with the URL bar**
![图片](https://github.com/christorange/VerticalFox/assets/89644868/7413fb48-c290-4be9-a38a-e9f6210489db)

**Comment by christorange** [comment]
Go to Extensions & Themes, enable light theme then your url bar will display normally.

<img width="221" alt="image" src="https://github.com/christorange/VerticalFox/assets/85213835/a6d33983-fbff-485c-9645-dc30885c0dbd">

<img width="725" alt="image" src="https://github.com/christorange/VerticalFox/assets/85213835/24f5d339-771e-4340-acc4-fa295f940b17">

The sidebar is shared between Sidebery, the History sidebar, Bookmarks sidebar, Synced Tabs sidebar, etc. If you want to leave the Sidebery sidebar visible and bring up the Manage History window (instead of the History sidebar) you can press `Ctrl+Shift+H`, and I suggest add history to toolbar for quick access

![image](https://github.com/christorange/VerticalFox/assets/85213835/46b0ba0d-3a1f-4b9b-a4e1-f81a67bb254e)
